name: $(BuildDefinitionName)_$(date:yyyyMMdd)$(rev:.r)
 
trigger: none
 
pr: none
 
stages :        
  - stage: arm_template_deploy
    jobs:
      - job: arm_template_deploy
        steps:
              - checkout: self
 
              - task: AzureResourceManagerTemplateDeployment@3
                inputs:
                  deploymentScope: 'Resource Group'
                  azureResourceManagerConnection: 'test'
                  subscriptionId: '42c5e824-82f0-40af-af25-2b70c870a7d2'
                  action: 'Create Or Update Resource Group'
                  resourceGroupName: 'admin'
                  location: 'eastus2'
                  templateLocation: 'Linked artifact'
                  csmFile: '$(System.DefaultWorkingDirectory)/updateManagement/template.json'
                  csmParametersFile: '$(System.DefaultWorkingDirectory)/updateManagement/parameters.json'
                  deploymentMode: 'Incremental'